// Copyright Fillipe Romero. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace FragmentTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grid)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Icon)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stackable)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Consumable)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Equipment)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemName)
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(PrimaryStat)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemType)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(FlavorText)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SellValue)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RequiredLevel)

	namespace StatMod
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(StatMod_1)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(StatMod_2)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(StatMod_3)
	}
}
